In [19]:
import torch
import numpy as np
print(torch.__version__)

1.12.0


In [13]:
torch.version.cuda

'11.3'

In [15]:
t = torch.tensor([1,2,3])
t

tensor([1, 2, 3])

In [17]:
a = [1,2,3,4]
a[2]

3

In [18]:
t = torch.Tensor()
type(t)

torch.Tensor

### PyTorch Tensors

In [20]:
t=torch.Tensor()
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


In [23]:
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([1.,2.,3.])

In [24]:
t1.dtype

torch.int64

In [25]:
t2.dtype

torch.float32

In [26]:
#Creating tensors from data
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [27]:
#First way
torch.Tensor(data) #Constructor

#Notice our tensor is showcased as floats

tensor([1., 2., 3.])

In [28]:
#Second way
torch.tensor(data) #Factory function

#Data type matches input data

tensor([1, 2, 3], dtype=torch.int32)

In [29]:
#Third way
torch.as_tensor(data)

#Same as second method

tensor([1, 2, 3], dtype=torch.int32)

In [30]:
#Fourth way
torch.from_numpy(data)

#Same as second method

tensor([1, 2, 3], dtype=torch.int32)

### Creation Options Without Data

In [31]:
torch.eye(2) #2d tensor

tensor([[1., 0.],
        [0., 1.]])

In [33]:
torch.zeros(2,2) #Rank 2 tensor with length of 2

tensor([[0., 0.],
        [0., 0.]])

In [34]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [35]:
torch.rand(2,2)

tensor([[0.2860, 0.2596],
        [0.1724, 0.6161]])

### Creating PyTorch Tensors - best options

In [36]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data) #factory function that returns an object - allow for more dynamic object creation
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

#The factory functions have more documentation than constructors

In [37]:
#Factory function allows us to set the data type
torch.tensor(np.array([1,2,3]), dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [38]:
data = np.array([1,2,3])

In [39]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data) #factory function that returns an object - allow for more dynamic object creation
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

#The factory functions have more documentation than constructors

In [40]:
data[0] = 0
data[1] = 0
data[2] = 0

In [41]:
#First two options create a separate copy
print(t1)
print(t2)

######### THERE'S A DIFFERENCE? ?? 

#Make tensors that share the object
print(t3) #MIRROR THE CHANGES
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([0, 0, 0], dtype=torch.int32)
tensor([0, 0, 0], dtype=torch.int32)


In [ ]:
#torch.tensor() is the BEST
#second option: torch.as_tensor() SECOND BEST

#### Reshaping Tensors

In [42]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [43]:
t.size()

torch.Size([3, 4])

In [44]:
t.shape

torch.Size([3, 4])

In [45]:
rank = len(t.shape)
print(rank)

2


In [46]:
torch.tensor(t.shape).prod()

tensor(12)

In [47]:
t.numel() #number of elements in the tensor

12

In [48]:
t.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [52]:
print(t.reshape(1,12))
print(t.reshape(1,12).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [53]:
print(t.reshape(1,12).squeeze())
print(t.reshape(1,12).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


In [54]:
print(t.reshape(1,12).squeeze().unsqueeze(dim=0))
print(t.reshape(1,12).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [ ]:
def flatten(t):
    t = t.reshpe(1,-1) #-1 in the second argument tells it to figure it out what the value should be.
    t = t.squeeze()
    return t

#### Concatenating Tensors

In [55]:
t1 = torch.tensor([
    [1,2],
    [3,4]
])

t2 = torch.tensor([
    [5,6],
    [7,8]
])

In [56]:
torch.cat((t1,t2), dim=0) #combining them row-wise

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [57]:
torch.cat((t1,t2), dim=1) #combining them column-wise

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

#### CNN Flatten Operation Visualized

In [58]:
t1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

t2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])

t3 = torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])

In [61]:
t = torch.stack((t1,t2,t3))
t.shape

torch.Size([3, 4, 4])

In [62]:
t

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

In [63]:
#Add color channel to the tensor
t = t.reshape(3,1,4,4)
t

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

In [64]:
t[0] #first image

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

In [65]:
t[0][0] #first color channel of image

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [ ]:
t[0][0][0] #first row of pixels in first color channel of first image

In [ ]:
t[0][0][0][0] #first pixel value in the first row of pixels in first color channel of first image

In [ ]:
#When we reshape for CNNs, we don't want to flatten the whole thing - only the image tensors in the batch tensors

In [66]:
#Flatten only image tensors - color channel + height and width channel
t.flatten(start_dim=1).shape #start_dim -> which axis to start with. Batch axis is 0 and color channel is 1


torch.Size([3, 16])

In [67]:
t.flatten(start_dim=1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

#### Element-wise tensor operations

In [68]:
t1 = torch.tensor([
    [1,2],
    [3,4]
])

t2 = torch.tensor([
    [5,6],
    [7,8]
])

In [69]:
t1[0]

tensor([1, 2])

In [70]:
t1[0][0]

tensor(1)

In [71]:
#Corresponding elements
t2[0][0] # 5 corresponds to 1

tensor(5)

In [76]:
t1 + 2

tensor([[3, 4],
        [5, 6]])

In [80]:
t1 + np.broadcast_to(2, t1.shape)

tensor([[3, 4],
        [5, 6]])

In [81]:
t1 = torch.tensor([
    [1,1],
    [1,1]
])

t2 = torch.tensor([2,4])

In [83]:
print(t2.shape)

torch.Size([2])


In [82]:
t1 + t2

tensor([[3, 5],
        [3, 5]])

#### Argmax and Reduction Ops

In [84]:
t = torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
])

In [85]:
t.sum()

tensor(8)

In [86]:
t.numel()

9

In [87]:
t.sum().numel()

1

In [89]:
t.sum().numel() < t.numel()

True

In [90]:
t.sum(dim=0)

tensor([2, 4, 2])

In [91]:
t.sum(dim=1)

tensor([1, 4, 3])

In [92]:
t.max()

tensor(3)

In [93]:
t.argmax()

tensor(7)

In [95]:
t.flatten()

tensor([0, 1, 0, 2, 0, 2, 0, 3, 0])